/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* Echo_IRQ */
#define Echo_IRQ__INTC_CORTEXM0P_ASSIGNED 1
#define Echo_IRQ__INTC_CORTEXM0P_MUX 8u
#define Echo_IRQ__INTC_CORTEXM0P_PRIORITY 2u
#define Echo_IRQ__INTC_NUMBER 92u
#define Echo_IRQ_INTC_CORTEXM0P_ASSIGNED 1
#define Echo_IRQ_INTC_CORTEXM0P_MUX 8u
#define Echo_IRQ_INTC_CORTEXM0P_PRIORITY 2u
#define Echo_IRQ_INTC_NUMBER 92u

/* UART_SCB_IRQ */
#define UART_SCB_IRQ__INTC_CORTEXM0P_ASSIGNED 1
#define UART_SCB_IRQ__INTC_CORTEXM0P_MUX 9u
#define UART_SCB_IRQ__INTC_CORTEXM0P_PRIORITY 3u
#define UART_SCB_IRQ__INTC_NUMBER 46u
#define UART_SCB_IRQ_INTC_CORTEXM0P_ASSIGNED 1
#define UART_SCB_IRQ_INTC_CORTEXM0P_MUX 9u
#define UART_SCB_IRQ_INTC_CORTEXM0P_PRIORITY 3u
#define UART_SCB_IRQ_INTC_NUMBER 46u

/* BLE_bless_isr */
#define BLE_bless_isr__INTC_CORTEXM0P_ASSIGNED 1
#define BLE_bless_isr__INTC_CORTEXM0P_MUX 3u
#define BLE_bless_isr__INTC_CORTEXM0P_PRIORITY 1u
#define BLE_bless_isr__INTC_NUMBER 24u
#define BLE_bless_isr_INTC_CORTEXM0P_ASSIGNED 1
#define BLE_bless_isr_INTC_CORTEXM0P_MUX 3u
#define BLE_bless_isr_INTC_CORTEXM0P_PRIORITY 1u
#define BLE_bless_isr_INTC_NUMBER 24u

/* UART_GPS_SCB_IRQ */
#define UART_GPS_SCB_IRQ__INTC_CORTEXM0P_ASSIGNED 1
#define UART_GPS_SCB_IRQ__INTC_CORTEXM0P_MUX 10u
#define UART_GPS_SCB_IRQ__INTC_CORTEXM0P_PRIORITY 3u
#define UART_GPS_SCB_IRQ__INTC_NUMBER 42u
#define UART_GPS_SCB_IRQ_INTC_CORTEXM0P_ASSIGNED 1
#define UART_GPS_SCB_IRQ_INTC_CORTEXM0P_MUX 10u
#define UART_GPS_SCB_IRQ_INTC_CORTEXM0P_PRIORITY 3u
#define UART_GPS_SCB_IRQ_INTC_NUMBER 42u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
