/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* UART_rx */
#define UART_rx_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_rx_0_INBUF_ENABLED 1u
#define UART_rx_0_INIT_DRIVESTATE 1u
#define UART_rx_0_INIT_MUXSEL 18u
#define UART_rx_0_INPUT_SYNC 2u
#define UART_rx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_rx_0_NUM 0u
#define UART_rx_0_PORT GPIO_PRT5
#define UART_rx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_rx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_rx_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_rx_INBUF_ENABLED 1u
#define UART_rx_INIT_DRIVESTATE 1u
#define UART_rx_INIT_MUXSEL 18u
#define UART_rx_INPUT_SYNC 2u
#define UART_rx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_rx_NUM 0u
#define UART_rx_PORT GPIO_PRT5
#define UART_rx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_rx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_tx */
#define UART_tx_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_tx_0_INBUF_ENABLED 0u
#define UART_tx_0_INIT_DRIVESTATE 1u
#define UART_tx_0_INIT_MUXSEL 18u
#define UART_tx_0_INPUT_SYNC 2u
#define UART_tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_tx_0_NUM 1u
#define UART_tx_0_PORT GPIO_PRT5
#define UART_tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_tx_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_tx_INBUF_ENABLED 0u
#define UART_tx_INIT_DRIVESTATE 1u
#define UART_tx_INIT_MUXSEL 18u
#define UART_tx_INPUT_SYNC 2u
#define UART_tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_tx_NUM 1u
#define UART_tx_PORT GPIO_PRT5
#define UART_tx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* finservo */
#define finservo_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define finservo_0_INBUF_ENABLED 0u
#define finservo_0_INIT_DRIVESTATE 1u
#define finservo_0_INIT_MUXSEL 8u
#define finservo_0_INPUT_SYNC 2u
#define finservo_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define finservo_0_NUM 6u
#define finservo_0_PORT GPIO_PRT9
#define finservo_0_SLEWRATE CY_GPIO_SLEW_FAST
#define finservo_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define finservo_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define finservo_INBUF_ENABLED 0u
#define finservo_INIT_DRIVESTATE 1u
#define finservo_INIT_MUXSEL 8u
#define finservo_INPUT_SYNC 2u
#define finservo_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define finservo_NUM 6u
#define finservo_PORT GPIO_PRT9
#define finservo_SLEWRATE CY_GPIO_SLEW_FAST
#define finservo_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* GreenLight */
#define GreenLight_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define GreenLight_0_INBUF_ENABLED 0u
#define GreenLight_0_INIT_DRIVESTATE 0u
#define GreenLight_0_INIT_MUXSEL 0u
#define GreenLight_0_INPUT_SYNC 2u
#define GreenLight_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define GreenLight_0_NUM 1u
#define GreenLight_0_PORT GPIO_PRT7
#define GreenLight_0_SLEWRATE CY_GPIO_SLEW_FAST
#define GreenLight_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define GreenLight_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define GreenLight_INBUF_ENABLED 0u
#define GreenLight_INIT_DRIVESTATE 0u
#define GreenLight_INIT_MUXSEL 0u
#define GreenLight_INPUT_SYNC 2u
#define GreenLight_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define GreenLight_NUM 1u
#define GreenLight_PORT GPIO_PRT7
#define GreenLight_SLEWRATE CY_GPIO_SLEW_FAST
#define GreenLight_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* trashservo */
#define trashservo_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define trashservo_0_INBUF_ENABLED 0u
#define trashservo_0_INIT_DRIVESTATE 1u
#define trashservo_0_INIT_MUXSEL 8u
#define trashservo_0_INPUT_SYNC 2u
#define trashservo_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define trashservo_0_NUM 2u
#define trashservo_0_PORT GPIO_PRT9
#define trashservo_0_SLEWRATE CY_GPIO_SLEW_FAST
#define trashservo_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define trashservo_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define trashservo_INBUF_ENABLED 0u
#define trashservo_INIT_DRIVESTATE 1u
#define trashservo_INIT_MUXSEL 8u
#define trashservo_INPUT_SYNC 2u
#define trashservo_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define trashservo_NUM 2u
#define trashservo_PORT GPIO_PRT9
#define trashservo_SLEWRATE CY_GPIO_SLEW_FAST
#define trashservo_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* thrustmotor */
#define thrustmotor_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define thrustmotor_0_INBUF_ENABLED 0u
#define thrustmotor_0_INIT_DRIVESTATE 1u
#define thrustmotor_0_INIT_MUXSEL 8u
#define thrustmotor_0_INPUT_SYNC 2u
#define thrustmotor_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define thrustmotor_0_NUM 6u
#define thrustmotor_0_PORT GPIO_PRT10
#define thrustmotor_0_SLEWRATE CY_GPIO_SLEW_FAST
#define thrustmotor_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define thrustmotor_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define thrustmotor_INBUF_ENABLED 0u
#define thrustmotor_INIT_DRIVESTATE 1u
#define thrustmotor_INIT_MUXSEL 8u
#define thrustmotor_INPUT_SYNC 2u
#define thrustmotor_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define thrustmotor_NUM 6u
#define thrustmotor_PORT GPIO_PRT10
#define thrustmotor_SLEWRATE CY_GPIO_SLEW_FAST
#define thrustmotor_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
